- .github/workflows/on_push-develop.yml
Reverts alphagov/di-mobile-android-onelogin-app#22
This ID token is required for the AWS credentials from assuming the mobile secrets role to persist.
Successfully tested on branch deployment here - https://github.com/alphagov/di-mobile-android-onelogin-app/actions/runs/6272447727
> Revert "Remove explicit permission from on push develop"

- config/actions/retrieve-secrets/action.yml
Update was-secrets-manager-actions to version 2.2.1
[DCMAW-6679](https://govukverify.atlassian.net/jira/software/c/projects/DCMAW/boards/371?selectedIssue=DCMAW-6679)
[DCMAW-6679]: https://govukverify.atlassian.net/browse/DCMAW-6679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DCMAW-6679] Update aws-secrets-manager-actions version to 2.2.1

- app/build.gradle.kts
Fixes the `java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/material/ColorsKt;` error seen in the release buildType
Resolves: DCMAW-6344
> Add material 2 as an implementation dep

- .github/CODEOWNERS
Aligns code ownership on this repository with documentation here https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/3791945770/Mobile+Platform+repositories+and+Github+Teams
> Add mobile platform team as codeowners on android one login app repository

- app/build.gradle.kts
- app/src/androidTest/java/uk/gov/onelogin/ui/login/WelcomeScreenKtTest.kt
- app/src/build/res/values/login_flow.xml
- app/src/main/java/uk/gov/onelogin/MainActivity.kt
- app/src/main/java/uk/gov/onelogin/MainActivityViewModel.kt
- app/src/main/java/uk/gov/onelogin/credentialchecker/CredentialChecker.kt
- app/src/main/java/uk/gov/onelogin/credentialchecker/CredentialCheckerModule.kt
- app/src/main/java/uk/gov/onelogin/credentialchecker/DeviceCredentialChecker.kt
- app/src/main/java/uk/gov/onelogin/login/WelcomeScreen.kt
- app/src/main/java/uk/gov/onelogin/ui/home/HomeRoutes.kt
- app/src/main/java/uk/gov/onelogin/ui/home/HomeScreen.kt
- app/src/main/java/uk/gov/onelogin/ui/home/PasscodeEnabledErrorScreen.kt
- app/src/production/res/values/login_flow.xml
- app/src/staging/res/values/login_flow.xml
- app/src/test/java/uk/gov/onelogin/MainActivityViewModelTest.kt
- app/src/test/java/uk/gov/onelogin/extensions/InstantExecutorExtension.kt
- app/src/test/java/uk/gov/onelogin/network/credentialchecker/DeviceCredentialCheckerTest.kt
- versions.properties
- add sts client_id
- add sts scope
Resolves: DCMAW-7624
- Create `CredentialChecker` interface and `DeviceCredentialChecker` implementation to check if phone has passcode/pin
- Add placeholder error screen if device is not secure
- refactor `MainActivityViewModel` to remove need for context within
Resolves: DCMAW-7798
> DCMAW-7798: Implement 'passcode enabled' check

- app/build.gradle.kts
- app/src/androidTest/java/uk/gov/onelogin/HomeScreenViewModelTest.kt
- app/src/debug/kotlin/uk/gov/onelogin/HiltTestActivity.kt
- app/src/main/java/uk/gov/onelogin/HomeScreenViewModel.kt
- app/src/main/java/uk/gov/onelogin/MainActivity.kt
- app/src/main/java/uk/gov/onelogin/MainActivityViewModel.kt
- app/src/main/java/uk/gov/onelogin/repositiories/TokenRepository.kt
- app/src/main/java/uk/gov/onelogin/repositiories/TokenRepositoryModule.kt
- app/src/main/java/uk/gov/onelogin/tokens/Keys.kt
- app/src/main/java/uk/gov/onelogin/tokens/Mapper.kt
- app/src/main/java/uk/gov/onelogin/tokens/TokenModule.kt
- app/src/main/java/uk/gov/onelogin/tokens/usecases/SaveToSecureStore.kt
- app/src/main/java/uk/gov/onelogin/tokens/usecases/SaveTokenExpiry.kt
- app/src/main/java/uk/gov/onelogin/ui/home/HomeRoutes.kt
- app/src/main/java/uk/gov/onelogin/ui/home/HomeScreen.kt
- app/src/test/java/uk/gov/onelogin/MainActivityViewModelTest.kt
- app/src/test/java/uk/gov/onelogin/extensions/CoroutinesTestExtension.kt
- app/src/test/java/uk/gov/onelogin/repostiories/TokenRepositoryTest.kt
- app/src/test/java/uk/gov/onelogin/tokens/MapperTest.kt
- app/src/test/java/uk/gov/onelogin/tokens/usecases/SaveTokenExpiryTest.kt
- config/styles/config/vocabularies/Base/accept.txt
- gradle/libs.versions.toml
- Create TokenRepository to handle saving the tokens in working memory
- Create SaveToSecureStore use case to handle saving to SecureStore instance and centralise the creation of the SharedPrefsStore instance. Ensures creation only happens when a BioPref has been set
- Create SaveTokenExpiry use case to handle saving the token expiry in shared prefs
- Keys object created to house keys related to the tokens being saved in shared prefs and secure storage etc.
- Mapper method handles mapping bio prefs to access control level for secure storage
- Change in MainActivityViewModel to stop saving the tokens in shared prefs and into the new repository instead
- HomeScreen now handles saving the tokens into SecureStore via methods in HomeScreenViewModel
- Add relevant tests
> feat/DCMAW-7898: Save Tokens to Secure Store

- app/src/main/java/uk/gov/onelogin/MainActivityViewModel.kt
- app/src/test/java/uk/gov/onelogin/MainActivityViewModelTest.kt
Make sure to set BioPref and initialise SecureStore when passcode pref is required
Resolves: DCMAW-8847
> fix/DCMAW-8847: Hanging Splash Screen Fix

- .githooks/pre-commit
- app/build.gradle.kts
- app/src/androidTest/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenKtTest.kt
- app/src/build/res/values/login_flow.xml
- app/src/main/java/uk/gov/onelogin/developer/DeveloperPanelScreen.kt
- app/src/main/java/uk/gov/onelogin/developer/tabs/auth/AuthTabScreen.kt
- app/src/main/java/uk/gov/onelogin/developer/tabs/auth/AuthTabScreenViewModel.kt
- app/src/main/java/uk/gov/onelogin/features/FeaturesModule.kt
- app/src/main/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenViewModel.kt
- app/src/main/java/uk/gov/onelogin/network/StsAuthenticationProvider.kt
- app/src/main/java/uk/gov/onelogin/network/data/TokenApiResponse.kt
- app/src/main/java/uk/gov/onelogin/network/di/NetworkModule.kt
- app/src/main/java/uk/gov/onelogin/network/di/NetworkUsecaseModule.kt
- app/src/main/java/uk/gov/onelogin/network/usecase/HelloWorldApiCall.kt
- app/src/main/res/values/endpoints.xml
- app/src/main/res/values/strings.xml
- app/src/production/res/values/login_flow.xml
- app/src/staging/res/values/login_flow.xml
- app/src/test/java/uk/gov/onelogin/network/usecase/HelloWorldApiCallTest.kt
- build.gradle.kts
- gradle/libs.versions.toml
- Creation of `AuthTabScreen` to live in the developer menu. This has two buttons to allow a happy and sad path call to `/hello-world` endpoint
- `AuthTabScreenViewModel` handles making the calls to hello world. Sad call temporarily deletes the stored access token to simulate an error
- STS endpoint feature is turned on
- Use case `HelloWorldApiCall` created to handle calls to `/hello-world` endpoint
- Necessary hilt modules created to provide http clients from the android-network module
- Slight changes in `WelcomeScreenViewModel` to fix calling the STS `/authorize` url
Resolves: DCMAW-8814
> feat/DCMAW-8814: Create HelloWorld sts call

- app/build.gradle.kts
- app/src/androidTest/java/uk/gov/onelogin/login/ui/splash/SplashScreenViewModelTest.kt
- app/src/androidTest/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenKtTest.kt
- app/src/androidTest/java/uk/gov/onelogin/signOut/ui/SignOutScreenKtTest.kt
- app/src/androidTest/java/uk/gov/onelogin/signOut/ui/SignOutScreenTest.kt
- app/src/androidTest/java/uk/gov/onelogin/signOut/ui/SignOutViewModelTest.kt
- app/src/main/java/uk/gov/onelogin/mainnav/ui/MainNavScreen.kt
- app/src/main/java/uk/gov/onelogin/signOut/domain/SignOutUseCase.kt
- app/src/main/java/uk/gov/onelogin/signOut/ui/SignOutScreen.kt
- app/src/main/java/uk/gov/onelogin/signOut/ui/SignOutViewModel.kt
- app/src/main/java/uk/gov/onelogin/wallet/DeleteWalletDataUseCase.kt
- app/src/main/java/uk/gov/onelogin/wallet/WalletModule.kt
- app/src/test/java/uk/gov/onelogin/signOut/domain/SignOutUseCaseTest.kt
- app/src/test/java/uk/gov/onelogin/wallet/DeleteWalletDataUseCaseTest.kt
- buildLogic/plugins/src/main/kotlin/uk.gov.onelogin.jvm-toolchains.gradle.kts
- features/build.gradle.kts
- gradle/libs.versions.toml
[DCMAW-9185](https://govukverify.atlassian.net/browse/DCMAW-9185)
**Description Of Changes:**
- update java version used to v17
- update walletSdk version - update other dependencies to newer versions to be compatible with the wallet sdk
- update all use cases dependent on deleteWalletData
- update Wallet module: new wallet impl and delete data use case
- amend/ write tests accordingly
**Evidence:**
AC3 cannot de demo-ed - there is a unit test for it.
AC1:
Scenario 1: Credentials deleted successfully when Wallet API is called
GIVEN I am a user on the strategic app
AND I’m on the Sign out confirmation page
WHEN I tap the 'Sign out and delete app data' CTA
THEN Wallet credential deletion API is called
AND my Wallet credentials are deleted …
> feat: Implement DeleteWalletData

- app/src/androidTest/java/uk/gov/onelogin/signOut/ui/SignedOutInfoAnalyticsViewModelTest.kt
- app/src/androidTest/java/uk/gov/onelogin/signOut/ui/SignedOutInfoScreenTest.kt
- app/src/main/java/uk/gov/onelogin/signOut/ui/SignedOutInfoAnalyticsViewModel.kt
- app/src/main/java/uk/gov/onelogin/signOut/ui/SignedOutInfoScreen.kt
- app/src/main/res/values/screen_ids.xml
[Ticket DCMAW-9635](https://govukverify.atlassian.net/browse/DCMAW-9635)
- Built on top of DCMAW-8381, so only the last 6 commits are actually this ticket until 8381 is merged
- Adds Preview to SignedOutInfo
- Adds Analytics to SignedOutInfoScreen
User has opted-in to analytics
AC1a: trackScreen analytics
GIVEN I have previously opted in to analytics
WHEN I land on the ‘You’ve been signed out' page
THEN the trackScreen analytics defined in the OpenAPI spec will be sent to GA4
AND the firebase Screen ID [screenView] is set to cfc50baa-4b56-4170-9707-cd05b60b6658
AC2a: trackEventLink analytics ('Sign in with GOV.UK One Login' link to authentication webview)
GIVEN I have previously opted in to analytics
AND I’m on the ‘You’ve been signed out' page
WHEN I click the ‘Sign in with GOV.UK One …
> Feat: DCMAW-9635

- app/src/androidTest/java/uk/gov/onelogin/login/ui/splash/SplashScreenTest.kt
- app/src/androidTest/java/uk/gov/onelogin/navigation/NavControllerExtTest.kt
- app/src/androidTest/java/uk/gov/onelogin/ui/error/update/UpdateRequiredAnalyticsViewModelTest.kt
- app/src/androidTest/java/uk/gov/onelogin/ui/error/update/UpdateRequiredBodyTest.kt
- app/src/androidTest/java/uk/gov/onelogin/ui/error/update/UpdateRequiredErrorScreenTest.kt
- app/src/main/java/uk/gov/onelogin/MainActivityViewModel.kt
- app/src/main/java/uk/gov/onelogin/navigation/NavControllerExt.kt
- app/src/main/java/uk/gov/onelogin/ui/error/update/UpdateRequiredAnalyticsViewModel.kt
- app/src/main/java/uk/gov/onelogin/ui/error/update/UpdateRequiredErrorScreen.kt
- app/src/main/res/values/screen_ids.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/uk/gov/onelogin/MainActivityViewModelTest.kt
- [Ticket DCMAW-9613](https://govukverify.atlassian.net/browse/DCMAW-9613)
- [GA4 Schema v3.1](https://govukverify.atlassian.net/wiki/spaces/PI/pages/3790995627/GA4+One+Login+Mobile+Application+Data+Schema+V3.1)
- Built on top of DCMAW-9635, so only the last 6 commits are actually this ticket until 9635 is merged
- Adds Preview to UpdateRequiredScreen
- Updates UpdateRequiredScreen to use Analytics
- Synchronises Analytics preference on App start
User has opted-in to analytics
AC1a: trackScreen analytics [opt-in]
GIVEN I have previously opted in to analytics
WHEN I land on the App update required page
THEN the trackScreen analytics defined in the OpenAPI spec will be sent to GA4
AND the firebase Screen ID [screenView] is set to ae56a0d6-072a-406f-84c7-83759aa4f942
AND no other screenView …
> Feat: DCMAW 9613

- app/src/main/java/uk/gov/onelogin/appinfo/AppInfoUtils.kt
- app/src/main/java/uk/gov/onelogin/appinfo/appversioncheck/data/AppVersionCheckImpl.kt
- app/src/test/java/uk/gov/onelogin/TestUtils.kt
- app/src/test/java/uk/gov/onelogin/appinfo/AppInfoUtilsTest.kt
- app/src/test/java/uk/gov/onelogin/appinfo/appversioncheck/AppVersionCheckImplTest.kt
- config/styles/config/vocabularies/Base/accept.txt
[DCMAW-10471](https://govukverify.atlassian.net/browse/DCMAW-10471)
- amend how the version is checked to strip any string given and use a regex pattern that would extract only
if that is found
- add missing condition to `AppVersionCheckImpl` to stop a check if the local version is higher than the remote one early in the flow
- 
**Evidence:**
- this has been unit tested but it cannot be evidenced until published to the PlayStore to see if the fix solved the bug. The ticket will stay in QA until merged and the PlayStore version is checked as working properly.
Definition Of Done Checklist:
[DCMAW-10471]: https://govukverify.atlassian.net/browse/DCMAW-10471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
> fix: Fix AppVersionCheck bug

- app/src/androidTest/java/uk/gov/onelogin/signOut/ui/SignOutBodyTest.kt
- app/src/androidTest/java/uk/gov/onelogin/signOut/ui/SignOutScreenTest.kt
- app/src/main/java/uk/gov/onelogin/signOut/ui/SignOutScreen.kt
- app/src/main/java/uk/gov/onelogin/signOut/ui/SignOutUIState.kt
- app/src/main/java/uk/gov/onelogin/signOut/ui/SignOutViewModel.kt
- app/src/main/res/values-cy/strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/uk/gov/onelogin/signOut/ui/SignOutUIStateTest.kt
- app/src/test/java/uk/gov/onelogin/signOut/ui/SignOutViewModelTest.kt
- [Ticket DCMAW-10331](https://govukverify.atlassian.net/browse/DCMAW-10331)
- Updates the copy on the SignOut page
- Adds SignOutUIState enum for future use
- This PR does not deal with the style / design changes that are required as they need to be done in the mobile-ui project
English
Welsh
- ~[ ] Complete all Acceptance Criteria within Jira ticket.~
- ~[ ] Review [Accessibility considerations].~
> Feat: DCMAW-10331 Update copy on the SignOut page

- app/src/androidTest/java/uk/gov/onelogin/e2e/LoginTest.kt
- app/src/androidTest/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenTest.kt
- app/src/androidTest/java/uk/gov/onelogin/signOut/ui/SignedOutInfoScreenTest.kt
- app/src/main/java/uk/gov/onelogin/appcheck/AppIntegrityImpl.kt
- app/src/main/java/uk/gov/onelogin/appcheck/FirebaseAppCheck.kt
- app/src/main/java/uk/gov/onelogin/appcheck/usecase/AppCheckUseCaseModule.kt
- app/src/main/java/uk/gov/onelogin/developer/tabs/appintegrity/AppIntegrityTabScreen.kt
- app/src/main/java/uk/gov/onelogin/developer/tabs/appintegrity/AppIntegrityTabViewModel.kt
- app/src/main/java/uk/gov/onelogin/tokens/TokenModule.kt
- app/src/main/java/uk/gov/onelogin/tokens/usecases/GetFromOpenSecureStore.kt
- app/src/main/java/uk/gov/onelogin/tokens/usecases/SaveToOpenSecureStore.kt
- app/src/test/java/uk/gov/onelogin/appcheck/AppIntegrityImplTest.kt
- gradle/libs.versions.toml
- Include checks on app integrity to see if saved attestation is either null;, expired or doesn't match the current public key
- Some facilitation bits added to the dev menu to show evidence
AC1 is not really possible to show however the screenshot below does show that when we receive a failure from making the attestation call we are directing to the `SignInError` screen
AC 2, 3 and 4
[DCMAW-10441.webm](https://github.com/user-attachments/assets/3516379c-de1c-4de6-a1bb-c3d68b2493c2)
[DCMAW-10441]: https://govukverify.atlassian.net/browse/DCMAW-10441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add conditional logic to App Integrity call

- app/src/androidTest/java/uk/gov/onelogin/e2e/LoginTest.kt
- app/src/androidTest/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenTest.kt
- app/src/androidTest/java/uk/gov/onelogin/signOut/ui/SignedOutInfoScreenTest.kt
- app/src/build/res/values/login_flow.xml
- app/src/main/java/uk/gov/onelogin/appcheck/AppIntegrity.kt
- app/src/main/java/uk/gov/onelogin/appcheck/AppIntegrityImpl.kt
- app/src/main/java/uk/gov/onelogin/appcheck/AttestationResult.kt
- app/src/main/java/uk/gov/onelogin/appcheck/usecase/AttestationApiCall.kt
- app/src/main/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenViewModel.kt
- app/src/main/java/uk/gov/onelogin/login/usecase/VerifyIdToken.kt
- app/src/test/java/uk/gov/onelogin/appcheck/AppIntegrityImplTest.kt
- app/src/test/java/uk/gov/onelogin/appcheck/usecase/AttestationApiCallTest.kt
- app/src/test/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenViewModelTest.kt
- gradle/libs.versions.toml
[DCMAW-10315](https://govukverify.atlassian.net/browse/DCMAW-10315)
- implement the updated finalise() method that allows for the AppIntegrityParameters - ClientAttestation and PoP - into the header of the auth request to get access tokens
- update the logic on the WelcomeScreenViewModel to allow for retry of retrieving a new attestation if the existing one cannot be accessed
**Evidence:**
**_AC1_**
Mobile Logs
```
2024-11-29 16:53:21.189  4916-4916  Authentica...Parameters uk.gov.onelogin.build                D  {OAuth-Client-Attestation=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImY2M2FlNDkxLWZjNzAtNGExNS05ZThhLTkwNWQ0OWEzZmU2ZCJ9.eyJpc3MiOiJodHRwczovL21vYmlsZS5idWlsZC5hY2NvdW50Lmdvdi51ayIsInN1YiI6ImJZcmN1UlZ2bnlsdkVnWVNTYkJqd1h6SHJ3SiIsImV …
```
> feat: Add AppIntegrityParameters into the authRequest header

- app/build.gradle.kts
- app/src/androidTest/java/uk/gov/onelogin/e2e/LoginTest.kt
- app/src/androidTest/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenTest.kt
- app/src/androidTest/java/uk/gov/onelogin/signOut/ui/SignedOutInfoScreenTest.kt
- app/src/androidTest/java/uk/gov/onelogin/tokens/usecases/GetFromTokenSecureStoreTest.kt
- app/src/main/java/uk/gov/onelogin/appcheck/AppIntegrityImpl.kt
- app/src/main/java/uk/gov/onelogin/login/state/LocalAuthStatus.kt
- app/src/main/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenViewModel.kt
- app/src/main/java/uk/gov/onelogin/login/usecase/HandleLogin.kt
- app/src/main/java/uk/gov/onelogin/tokens/TokenModule.kt
- app/src/main/java/uk/gov/onelogin/tokens/usecases/GetFromOpenSecureStore.kt
- app/src/main/java/uk/gov/onelogin/tokens/usecases/GetFromTokenSecureStore.kt
- app/src/main/java/uk/gov/onelogin/tokens/usecases/GetPersistentId.kt
- app/src/main/java/uk/gov/onelogin/tokens/usecases/SaveToOpenSecureStore.kt
- app/src/test/java/uk/gov/onelogin/MainActivityViewModelTest.kt
- app/src/test/java/uk/gov/onelogin/appcheck/AppIntegrityImplTest.kt
- app/src/test/java/uk/gov/onelogin/login/ui/splash/SplashScreenViewModelTest.kt
- app/src/test/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenViewModelTest.kt
- app/src/test/java/uk/gov/onelogin/login/usecase/HandleLoginTest.kt
- app/src/test/java/uk/gov/onelogin/login/usecase/SaveTokensTest.kt
- app/src/test/java/uk/gov/onelogin/network/StsAuthenticationProviderTest.kt
- app/src/test/java/uk/gov/onelogin/repostiories/TokenRepositoryTest.kt
- app/src/test/java/uk/gov/onelogin/tokens/usecases/GetPersistentIdImplTest.kt
- gradle/libs.versions.toml
[DCMAW-9701](https://govukverify.atlassian.net/browse/DCMAW-9701)
- update secure store and authentication versions
- update the relevant modules to now use the secure store again (`AppIntegrity` and Tokens and `HandleLogin`) and remove temporary use of `SharedPrefs`
- secure store returns a Map<String, String> which needs to be
handled approriately for each use case
- update tests
https://github.com/user-attachments/assets/d219b505-84b8-4907-b858-5926db2a329f
[DCMAW-9701]: https://govukverify.atlassian.net/browse/DCMAW-9701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Update to the refactored secure store

- app/src/androidTest/java/uk/gov/onelogin/feature/unavailable/ui/AppUnavailableBodyTest.kt
- app/src/androidTest/java/uk/gov/onelogin/feature/unavailable/ui/AppUnavailableScreenTest.kt
- app/src/androidTest/java/uk/gov/onelogin/ui/error/ErrorGraphObjectTest.kt
- app/src/main/java/uk/gov/onelogin/feature/unavailable/ui/AppUnavailableScreen.kt
- app/src/main/java/uk/gov/onelogin/ui/error/ErrorGraphObject.kt
- app/src/main/java/uk/gov/onelogin/ui/error/ErrorRoutes.kt
- app/src/main/res/values-cy/strings.xml
- app/src/main/res/values/strings.xml
- UI for the App unavailable page only
- Content description matches the one used for the same icon elsewhere i.e. nothing
This PR deliberately does not have the acceptance criteria for showing the screen, just the UI and back button only.
English
Welsh
Scenario 4: User taps hardware back button the ‘App unavailable’ page 
GIVEN I’m a user on the strategic app 
AND I'm on the ‘App unavailable’ page
WHEN I tap the hardware back button
THEN I exit the app
https://github.com/user-attachments/assets/d1f99e76-1e16-4361-b8de-fa10ac33a1da
[DCMAW-9823]: …
> Feat: DCMAW 9823 App unavailable page

- app/src/androidTest/java/uk/gov/onelogin/core/utils/AndroidUriParserTest.kt
- app/src/androidTest/java/uk/gov/onelogin/e2e/LoginTest.kt
- app/src/androidTest/java/uk/gov/onelogin/login/ui/splash/SplashScreenTest.kt
- app/src/main/java/uk/gov/onelogin/core/delete/Module.kt
- app/src/main/java/uk/gov/onelogin/core/utils/UriParser.kt
- app/src/main/java/uk/gov/onelogin/core/utils/UtilsModule.kt
- app/src/main/java/uk/gov/onelogin/login/ui/splash/SplashScreenViewModel.kt
- app/src/main/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenViewModel.kt
- app/src/main/java/uk/gov/onelogin/login/usecase/HandleLocalLogin.kt
- app/src/main/java/uk/gov/onelogin/login/usecase/HandleLoginRedirect.kt
- app/src/main/java/uk/gov/onelogin/login/usecase/HandleRemoteLogin.kt
- app/src/main/java/uk/gov/onelogin/login/usecase/UseCaseModule.kt
- app/src/test/java/uk/gov/onelogin/appcheck/AppIntegrityImplTest.kt
- app/src/test/java/uk/gov/onelogin/login/ui/splash/SplashScreenViewModelTest.kt
- app/src/test/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenViewModelTest.kt
- app/src/test/java/uk/gov/onelogin/login/usecase/HandleLocalLoginTest.kt
- app/src/test/java/uk/gov/onelogin/login/usecase/HandleLoginRedirectTest.kt
- app/src/test/java/uk/gov/onelogin/login/usecase/HandleRemoteLoginTest.kt
The main idea is to break up the complexity of the `WelcomeScreenViewModel`. This refactor hasn't reduced the constructor parameters tooo much unfortunately however the general complexity of the view model has been reduced.
- Remove `LoginSession` calls from `WelcomeScreenViewiodel`
- HandLeRemoteLogin.kt handles logic to do with starting the signing process via the *LoginSession •present()• and getting the client attestation
- HandleLoginRedirect.kt handles the response back from the login redirect, sets up the necessary bits for app integrity (attestation and PoP) to attach to the /token call to complete login
- Uri parser created for ease of testing
> refactor: WelcomeScreenViewModel

- docs/developer-setup/app-integrity.md
- docs/developer-setup/git-hooks.md
Just a little update to explain the situation with the Firebase debug secret
> docs: Adding documentation for app integrity setup

- app/src/androidTest/java/uk/gov/onelogin/login/ui/welcome/SignInAnalyticsViewModelTest.kt
- app/src/androidTest/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenTest.kt
- app/src/androidTest/java/uk/gov/onelogin/signOut/ui/SignedOutInfoAnalyticsViewModelTest.kt
- app/src/androidTest/java/uk/gov/onelogin/signOut/ui/SignedOutInfoScreenTest.kt
- app/src/build/res/values/login_flow.xml
- app/src/main/java/uk/gov/onelogin/features/AvailableFeatures.kt
- app/src/main/java/uk/gov/onelogin/features/FeaturesModule.kt
- app/src/main/java/uk/gov/onelogin/features/StsFeatureFlag.kt
- app/src/main/java/uk/gov/onelogin/login/ui/welcome/SignInAnalyticsViewModel.kt
- app/src/main/java/uk/gov/onelogin/login/usecase/HandleRemoteLogin.kt
- app/src/main/java/uk/gov/onelogin/signOut/ui/SignedOutInfoAnalyticsViewModel.kt
- app/src/production/res/values/login_flow.xml
- app/src/staging/res/values/login_flow.xml
- app/src/test/java/uk/gov/onelogin/features/AvailableFeaturesTest.kt
- app/src/test/java/uk/gov/onelogin/login/usecase/HandleRemoteLoginTest.kt
[DCMAW-9510](https://govukverify.atlassian.net/browse/DCMAW-9510)
- remove `StsFeatureFlag`
**Evidence:**
_Build_
https://github.com/user-attachments/assets/754c5bae-1e6e-4129-b8f3-492045f37d55
_Staging_
https://github.com/user-attachments/assets/0ea64692-cf91-4048-9dd2-84b8e22a3d8a
Resolves: DCMAW-9510
[DCMAW-9510]: https://govukverify.atlassian.net/browse/DCMAW-9510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Remove STS Feature Flag

- app/build.gradle.kts
- app/src/androidTest/java/uk/gov/onelogin/ui/home/HomeScreenKtTest.kt
- app/src/main/java/uk/gov/onelogin/login/ui/splash/SplashScreen.kt
- app/src/main/java/uk/gov/onelogin/signOut/ui/SignOutScreen.kt
- app/src/main/java/uk/gov/onelogin/signOut/ui/SignedOutInfoScreen.kt
- app/src/main/java/uk/gov/onelogin/ui/error/ErrorGraphObject.kt
- app/src/main/java/uk/gov/onelogin/ui/home/HomeScreen.kt
- app/src/main/java/uk/gov/onelogin/ui/home/HomeScreenViewModel.kt
- app/src/test/java/uk/gov/onelogin/ui/home/HomeScreenViewModelTest.kt
- build.gradle.kts
- gradle/libs.versions.toml
[DCMAW-10992](https://govukverify.atlassian.net/browse/DCMAW-10992)
**Description Of Changes:**
- update `compileSdkVersion` and `targetSdkVersion` to 35 to enable use of `CriOrchestratorSdk` which uses `androidx.activity` version 1.10.0
- update all instances of using `LocalContext.current` as `FragmentActivity` to `LocalActivity.current`
- add temporary functionality to display the instance of `CriOrchestratorSdk` 
**Evidence:**
Video showing regression, after `CriOrchestrator` integration, the app works as expected (as the instance of the `CriOrchestrator` is initialised on the `HomeScreen`)
https://github.com/user-attachments/assets/62795a3a-35e0-4a0e-89bc-3134c9e513d1
Logs showing instance initialised:
```
2025-01-29 13:37:34.519  8260-8260  CriIOrches...orInstance …
```
> feat: Integrate CriOrchestrator in the one-login app

- app/src/main/AndroidManifest.xml
[DCMAW-10252](https://govukverify.atlassian.net/browse/DCMAW-10252)
- amend AndroidManifest to remove `uk.gov.android.securestore.TestActivity` which allows for only one launcher when running the app
**Evidence:**
https://github.com/user-attachments/assets/60c148d9-1c12-48d2-aee7-2bac343a5cca
Resolves: DCMAW-10252
[DCMAW-10252]: https://govukverify.atlassian.net/browse/DCMAW-10252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Amend AndroidManifest to remove `uk.gov.android.securestore.TestActivity`

- app/proguard-rules.pro
- used the wrong pro-guard rule - missing classes should use `dontwarn`, while missing dependencies, `keep` is used for runtime classes
Resolves: DCMAW-10693
> fix: Amend pro-guard rules

- app/src/androidTest/java/uk/gov/onelogin/login/ui/biooptin/BioOptInAnalyticsViewModelTest.kt
- app/src/androidTest/java/uk/gov/onelogin/signOut/ui/SignOutAnalyticsViewModelTest.kt
Very simple change to move any existing `AnalyticsViewModel` test which  check multiple of the same `TrackEvent` types to use the recently introduced `TrackEventTestCase`
> refactor: Update AnalyticsViewModel test

- core/src/main/res/values-cy/strings.xml
- core/src/main/res/values/strings.xml
- features/src/androidTest/java/uk/gov/onelogin/features/error/ui/auth/AuthErrorScreenTest.kt
- features/src/androidTest/java/uk/gov/onelogin/features/error/ui/generic/GenericErrorScreenTest.kt
- features/src/main/java/uk/gov/onelogin/features/error/ui/auth/AuthErrorScreen.kt
- features/src/main/java/uk/gov/onelogin/features/error/ui/auth/AuthErrorViewModel.kt
- features/src/main/java/uk/gov/onelogin/features/error/ui/generic/GenericErrorScreen.kt
- features/src/test/java/uk/gov/onelogin/features/error/ui/auth/AuthErrorViewModelTest.kt
The `AuthErrorScreen` has been changed from an ErrorScreen template to a LandingPage template. This is mostly because the LandingPage uses M3 theme and is a little more inline with our current approach for UI. Having said that, it is still not perfect, but in the interests of time, using the template seems the best solution.
With wallet:
https://github.com/user-attachments/assets/625b760e-8d0b-4318-a1ce-c0cc0bc17fbd
Without Wallet:
https://github.com/user-attachments/assets/23ac055f-2bb8-4dc2-bd6e-4dd6025dd9a5
[DCMAW-10097]: https://govukverify.atlassian.net/browse/DCMAW-10097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DCMAW-11101]: https://govukverify.atlassian.net/browse/DCMAW-11101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …
> feat: Changing layout and copy of AuthErrorScreen

- app/src/androidTest/java/uk/gov/onelogin/navigation/graphs/LoginGraphObjectTest.kt
- app/src/main/java/uk/gov/onelogin/navigation/graphs/ErrorGraphObject.kt
- app/src/main/java/uk/gov/onelogin/navigation/graphs/LoginGraphObject.kt
- features/src/main/java/uk/gov/onelogin/features/login/ui/signin/biooptin/BioOptInAnalyticsViewModel.kt
- features/src/main/java/uk/gov/onelogin/features/login/ui/signin/biooptin/BiometricsOptInScreen.kt
- features/src/main/java/uk/gov/onelogin/features/login/ui/signin/splash/SplashScreen.kt
- features/src/main/java/uk/gov/onelogin/features/login/ui/signin/welcome/WelcomeScreen.kt
- features/src/main/java/uk/gov/onelogin/features/login/ui/signin/welcome/WelcomeScreenViewModel.kt
- features/src/main/java/uk/gov/onelogin/features/optin/ui/OptInScreen.kt
- features/src/main/java/uk/gov/onelogin/features/signout/ui/SignOutScreen.kt
- features/src/test/java/uk/gov/onelogin/features/login/ui/biooptin/BioOptInAnalyticsViewModelTest.kt
- features/src/test/java/uk/gov/onelogin/features/login/ui/biooptin/BioOptInScreenTest.kt
- features/src/test/java/uk/gov/onelogin/features/login/ui/splash/SplashScreenTest.kt
- features/src/test/java/uk/gov/onelogin/features/login/ui/welcome/WelcomeScreenTest.kt
- features/src/test/java/uk/gov/onelogin/features/login/ui/welcome/WelcomeScreenViewModelTest.kt
- features/src/test/java/uk/gov/onelogin/features/optin/ui/OptInScreenTest.kt
- update the system back button for login screens (including `WelcomeScreen`, `BiometricsOptInScreen`, `SplashScreen` and the nav graph
- update sign out back button behviour on `SignOuScreen` and `ErrorGraphObject`
- add missing analytics GA4 event for `BiometricsOptInScreen`
**Evidence:**
The only behaviour for these screens that could not be met is the one on login redirect loading screen(point 5 in teh documentation) - at the moment the back-button is enable now, so it will go back to the `WebView` - the landing page on redirect is just a composable popped on top of the welcome screen - although the launcher job is getting cancelled when pressing back, the `handleLoginRedirect` is not a job. We can maybe disable the back button to not get this weird …
> feat: Update back button behaviour for login and sign out screens

- gradle/libs.versions.toml
Simply bumping to next version to include addition of `typ` header changes
https://github.com/user-attachments/assets/a1b07a81-d637-471a-9bd6-a291bba8e633
[DCMAW-11880]: https://govukverify.atlassian.net/browse/DCMAW-11880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: DCMAW-11880 update to latest auth version

- .github/dependabot.yml
- update dependabot to group minor and patches into one PR rather than individual ones for each update/ upgrade
> ci: Update dpeendabot to group patches and minors updates

- .github/dependabot.yml
- amend wrong indentation on previous update
> ci: Format wrong indentation for `dependabot.yml`

- app/src/main/java/uk/gov/onelogin/MainActivityViewModel.kt
- app/src/main/java/uk/gov/onelogin/navigation/graphs/ErrorGraphObject.kt
- features/src/main/java/uk/gov/onelogin/features/login/ui/signin/biooptin/BiometricsOptInScreen.kt
- features/src/main/java/uk/gov/onelogin/features/login/ui/signin/splash/SplashScreen.kt
- features/src/main/java/uk/gov/onelogin/features/login/ui/signin/welcome/WelcomeScreen.kt
- features/src/main/java/uk/gov/onelogin/features/login/ui/signin/welcome/WelcomeScreenViewModel.kt
- features/src/main/java/uk/gov/onelogin/features/signout/domain/SignOutUseCase.kt
- features/src/main/java/uk/gov/onelogin/features/signout/domain/SignOutUseCaseImpl.kt
- features/src/main/java/uk/gov/onelogin/features/signout/ui/SignOutScreen.kt
- features/src/main/java/uk/gov/onelogin/features/signout/ui/SignOutViewModel.kt
- features/src/main/java/uk/gov/onelogin/features/signout/ui/SignedOutInfoScreen.kt
- features/src/main/java/uk/gov/onelogin/features/signout/ui/SignedOutInfoViewModel.kt
- features/src/main/java/uk/gov/onelogin/features/wallet/domain/DeleteWalletDataUseCase.kt
- features/src/test/java/uk/gov/onelogin/features/login/ui/welcome/WelcomeScreenViewModelTest.kt
- features/src/test/java/uk/gov/onelogin/features/signout/domain/SignOutUseCaseTest.kt
- features/src/test/java/uk/gov/onelogin/features/signout/ui/SignOutScreenTest.kt
- features/src/test/java/uk/gov/onelogin/features/signout/ui/SignOutViewModelTest.kt
- features/src/test/java/uk/gov/onelogin/features/signout/ui/SignedOutInfoScreenTest.kt
- features/src/test/java/uk/gov/onelogin/features/signout/ui/SignedOutInfoViewModelTest.kt
- features/src/test/java/uk/gov/onelogin/features/wallet/domain/DeleteWalletDataUseCaseTest.kt
- gradle/libs.versions.toml
**No ticket**
- replace `LocalContext.current` with `LocalActivity.current` when cast to either `Activity` of `FragmentActivity` - this is due to Wallet using `androidx.activity:activity` v1.10 or higher
- remove the activity required for `deleteAllDataUseCase` and all classes and functions that where passing activity for that only reason - it seems not to be required with the new sdk version
> build: Update Wallet Sdk version to latest

- app/src/main/java/uk/gov/onelogin/MainActivityViewModel.kt
- app/src/test/java/uk/gov/onelogin/MainActivityViewModelTest.kt
###Description
-  move logout logic to `onStop` in `MainActivity`
https://github.com/user-attachments/assets/9d8f4d54-40cd-4b13-a133-3aa3e7f2bddf
This evidence is shown on `Build` flavour so we don't see the camera however it shows fixing of the logout error which was the root problem.
> feat: DCMAW-12564 Fixing logout bug

- app/build.gradle.kts
- app/src/androidTest/java/uk/gov/onelogin/mainnav/ui/MainNavScreenTest.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/uk/gov/onelogin/MainActivity.kt
- app/src/main/java/uk/gov/onelogin/MainActivityViewModel.kt
- app/src/main/java/uk/gov/onelogin/mainnav/ui/MainNavScreen.kt
- app/src/main/java/uk/gov/onelogin/wallet/WalletRepositoryModule.kt
- app/src/test/java/uk/gov/onelogin/MainActivityViewModelIntentTest.kt
- app/src/test/java/uk/gov/onelogin/MainActivityViewModelTest.kt
- features/src/main/java/uk/gov/onelogin/features/featureflags/domain/FeatureFlagSetterImpl.kt
- features/src/main/java/uk/gov/onelogin/features/login/ui/signin/splash/SplashScreen.kt
- features/src/main/java/uk/gov/onelogin/features/wallet/data/WalletRepository.kt
- features/src/main/java/uk/gov/onelogin/features/wallet/ui/WalletScreen.kt
- features/src/main/java/uk/gov/onelogin/features/wallet/ui/WalletScreenViewModel.kt
- features/src/test/java/uk/gov/onelogin/features/featureflags/domain/FeatureFlagSetterImplTest.kt
- features/src/test/java/uk/gov/onelogin/features/wallet/data/WalletRepositoryTest.kt
- features/src/test/java/uk/gov/onelogin/features/wallet/ui/WalletScreenTest.kt
- features/src/test/java/uk/gov/onelogin/features/wallet/ui/WalletScreenViewModelTest.kt
- gradle/libs.versions.toml
- Create WalletRepository to store deeplink credential
- Change MainActivity launch mode in manifest to singleTask
- Make wallet initially enabled for build env
- Handle wallet deeplink when app active with no local auth on device
Resolves: [DCMAW-8902](https://govukverify.atlassian.net/browse/DCMAW-8902)
[DCMAW-8902]: https://govukverify.atlassian.net/browse/DCMAW-8902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
AC3: 
https://github.com/user-attachments/assets/3ea6e796-e854-4853-b8e9-6b5a3d90c31e
AC4:
[DCMAW-8902-AC4.webm](https://github.com/user-attachments/assets/51221fb2-78d7-48d3-a96d-ce65030bc610)
AC5:
Note that a "Something went wrong" error screen is displayed in the middle of this process. This is a pre existing bug which is being …
> User must authenticate when deep linking into the Wallet

- .github/dependabot.yml
Provide Dependabot with details of the GOV.UK One Login GitHub Maven repository and authentication details so that it can be used to update internal dependencies.
> chore(deps): enable GOV.UK One Login packages to be updated by Dependabot

- features/src/main/java/uk/gov/onelogin/features/error/ui/SignOutErrorScreen.kt
- features/src/main/java/uk/gov/onelogin/features/error/ui/signin/SignInErrorScreen.kt
- features/src/test/java/uk/gov/onelogin/features/error/ui/signin/SignInErrorScreenTest.kt
- Moving the last couple of Error Screens onto the `patterns.ErrorScreen`
[DCMAW-13448.webm](https://github.com/user-attachments/assets/fa9e1f61-21cb-4d6b-9846-01ecd1915946)
[DCMAW-13448]: https://govukverify.atlassian.net/browse/DCMAW-13448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: move error screens onto M3 `ErrorScreen`

- core/src/main/res/values-cy/strings.xml
- core/src/main/res/values/urls.xml
- the same link is used in 3 different instances (two on `SettingsScreen` and one on `OptInScreen`)
- [DCMAW-13532](https://govukverify.atlassian.net/browse/DCMAW-13532)
https://github.com/user-attachments/assets/0ff615e5-c7d0-4eb0-a240-b2fed0d00b08
https://github.com/user-attachments/assets/995d1196-3fad-4b40-bba5-3b737744cf20
[Sonar cloud report]: https://sonarcloud.io/project/overview?id=wallet-mobile-android
[DCMAW-13345]: https://govukverify.atlassian.net/browse/DCMAW-13345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Resolves: DCMAW-13532
[DCMAW-13532]: https://govukverify.atlassian.net/browse/DCMAW-13532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
> feat: Update the privacy link

- features/src/main/java/uk/gov/onelogin/features/home/ui/HomeScreen.kt
- features/src/main/java/uk/gov/onelogin/features/settings/ui/SettingsScreen.kt
- Remove duplicate bottom padding from Home and Settings screens
[bottom_nav_bar_fix_evidence.webm](https://github.com/user-attachments/assets/2394dfc2-3d43-4092-8c83-8926bad8eee8)
[DCMAW-13889]: https://govukverify.atlassian.net/browse/DCMAW-13889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCMAW-13889: Bottom navigation bar is disproportionately large

- gradle/libs.versions.toml
- this fix will allow a user to use fingerprint only - passcodes are not supported (this will be implemented with a further change to how we handle that)
Resolves: DCMAW-13750
> fix: Bump version for secure-store that fixes the API29 localauth loop

- app/src/main/java/uk/gov/onelogin/login/appintegrity/FirebaseAppCheck.kt
- add additional catch to get any other errors besides the FirebaseException
> fix: Catch generic errors on FirebaseAppCheck

- .github/workflows/on_push-main.yml
- config/actions/get-next-version-from-commit-message/action.yml
- fixed the versioning and tag push when on-merge-main
Successful versioning: https://github.com/govuk-one-login/mobile-android-one-login-app/actions/runs/16117860439/job/45475872928
There's still a couple of other things that haven't been tested since last change to the versioning process - these can't be tested before getting it merged (e.g. push the tag, etc), so there might be additional changes after this gets merged if any issues are noticed.
> ci: Fix getting the latest version from last commit

- features/src/main/java/uk/gov/onelogin/features/login/ui/signin/welcome/WelcomeScreen.kt
- use the `CentreAlingedScreen` API that allows for custom implementation 
Evidence:
https://github.com/user-attachments/assets/8e81ead4-a28f-4d9b-b6b7-1bb20acb93aa
Resolves: DCMAW-14637
> fix: Change implementation for SignInScreen to fix accessibility

- app/src/main/java/uk/gov/onelogin/MainActivity.kt
- app/src/main/java/uk/gov/onelogin/MainActivityViewModel.kt
- app/src/main/java/uk/gov/onelogin/mainnav/ui/MainNavScreen.kt
- app/src/main/java/uk/gov/onelogin/mainnav/ui/MainNavViewModel.kt
- features/src/main/java/uk/gov/onelogin/features/wallet/data/WalletRepository.kt
- features/src/test/java/uk/gov/onelogin/features/wallet/data/WalletRepositoryTest.kt
- features/src/test/java/uk/gov/onelogin/features/wallet/ui/WalletScreenViewModelTest.kt
This issue would only happen when the app is open (int he background) and a credential has already been added and removed from he Wallet (it seems the deep link was persisted)
**Changes:**
- add functionality to clear the deep link and credential off saved in memory after it's been passed to the `WalletSdk`
- add a check to `finish()` the intent when `onNewIntent` is called - this allows to reset the previously existing intent - this is done only when the user comes in via deep link to add a Wallet credential
- separate the `WalletScreenViewModel` and the `MainNavViewModel` to allow for specific behaviour that allows the user to add a credential when the app is in memory
https://github.com/user-attachments/assets/0188ed6a-eb1a-4f4b-8a62-4a5c892577c1
Resolves: DCMAW-14763
> fix: Fix deeplink not working properly when app is in memory

- app/src/main/java/uk/gov/onelogin/OneLoginApplication.kt
- add functionality to check if a debugger is connected when in release and if yes, kill the app
Resolves: DCMAW-14408
> fix: Add functionality to detect debugger attached and kill app

- app/src/build/res/xml/network_security_config.xml
- app/src/integration/res/xml/network_security_config.xml
- app/src/main/AndroidManifest.xml
- app/src/production/res/xml/network_security_config.xml
- app/src/staging/res/xml/network_security_config.xml
The change on back-end hasn't been done, so cannot be tested, but that is dependent on this and the iOS equivalent getting merged in.
[DCMAW-14910](https://govukverify.atlassian.net/browse/DCMAW-14910)
[app_accepts_both_links.webm](https://github.com/user-attachments/assets/141ed286-17c3-4ec0-93c1-6dfb8d465d80)
Resolves: DCMAW-14910
[DCMAW-14910]: https://govukverify.atlassian.net/browse/DCMAW-14910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add additional domain for login deeplinking into the app

- gradle/libs.versions.toml
Reverts govuk-one-login/mobile-android-one-login-app#645 due to breaking the network requests
> build: Revert "build(deps): bump io.ktor:ktor-client-mock from 3.1.3 to 3.3.0"
