.github/workflows/on_push-develop.yml, .github/workflows/on_push-release.yml, config/actions/retrieve-secrets/action.yml
=> Pass arn as input

config/actions/retrieve-secrets/action.yml
=> Update configure-aws-credentials to v3

.github/workflows/on_pull_request.yml
=> Add id-token permission

.github/workflows/on_schedule.yml
=> Fix scheduled job

.github/workflows/on_schedule.yml
=> Pass arch correctly in scheduled

.github/workflows/on_push-develop.yml, .github/workflows/on_push-release.yml
=> Add permissions

config/actions/retrieve-secrets/action.yml
=> Fix up secrets

config/actions/clean-workspace/action.yml, config/actions/retrieve-secrets/action.yml
=> Add missing `shell` property

.github/workflows/on_pull_request.yml, config/actions/retrieve-secrets/action.yml
=> Remove debug steps

.github/workflows/on_push-develop.yml, .github/workflows/on_push-release.yml
=> Remove explicit permissions from workflow files

.github/workflows/on_push-develop.yml
=> Remove explicit permission from on push develop

config/actions/retrieve-secrets/action.yml
=> Use V2 secrets

app/build.gradle.kts, app/src/main/java/uk/gov/onelogin/MainActivity.kt, app/src/main/java/uk/gov/onelogin/components/appbar/GdsAppBar.kt, app/src/main/java/uk/gov/onelogin/components/navigation/GdsNavigationBar.kt, app/src/main/java/uk/gov/onelogin/login/WelcomeScreen.kt, settings.gradle.kts
=> Chore: update to UI v2.0.0

app/src/build/res/values/login_flow.xml, app/src/main/java/uk/gov/onelogin/login/UriBuilder.kt, app/src/staging/res/values/login_flow.xml, settings.gradle.kts
- Update url build with the correct query parameters
- Update url staging with the correct query parameters
Video evidence for **Staging** 
https://github.com/govuk-one-login/mobile-android-one-login-app/assets/113670948/a68d4003-db43-4181-b5a0-9b33fefb3f52
=> DCMAW-7076:Android | Initiate login

.github/workflows/on_push-develop.yml
Note: This is temporary while the certs are rotated for staging. We _will_ be building both staging and build once this is complete.
Resolves: DCMAW-6344
=> Switch from staging to build for releases

.github/workflows/on_push-develop.yml
=> Build from develop for both build and staging

app/src/build/res/values/login_flow.xml, app/src/dev/res/values/login_flow.xml, app/src/integration/res/values/login_flow.xml
Resolves: DCMAW-7422
**Evidence**
_Staging_
_Build_
=> Correct auth stub URL for build

.github/workflows/on_pull_request.yml, app/build.gradle.kts, gradle/libs.versions.toml
Resolves: DCMAW-6886
Fixes: https://github.com/govuk-one-login/mobile-android-one-login-app/actions/runs/6951094614/job/18912462497#step:9:255
=> Add missing dep for release

app/src/androidTest/java/uk/gov/onelogin/AppRoutesTest.kt, app/src/androidTest/java/uk/gov/onelogin/home/HomeScreenKtTest.kt, app/src/androidTest/java/uk/gov/onelogin/login/LoginTestRoutes.kt, app/src/main/java/uk/gov/onelogin/MainActivity.kt, app/src/main/java/uk/gov/onelogin/MainActivityViewModel.kt, app/src/main/java/uk/gov/onelogin/home/HomeRoutes.kt, app/src/main/java/uk/gov/onelogin/home/HomeScreen.kt, app/src/main/java/uk/gov/onelogin/login/LoginRoutes.kt, app/src/main/java/uk/gov/onelogin/network/auth/AuthCodeExchange.kt, app/src/main/java/uk/gov/onelogin/network/auth/response/TokenResponse.kt, app/src/main/res/values/strings.xml
Resolves: DCMAW-7447
https://github.com/govuk-one-login/mobile-android-one-login-app/assets/113696444/17405745-3088-4204-a57c-28f29d4e9958
https://github.com/govuk-one-login/mobile-android-one-login-app/assets/113696444/23cfa44a-e2a5-4c89-bc40-c8a1a396f781
=> Refactor for Home screen

.github/workflows/on_pull_request.yml, app/build.gradle.kts, app/src/main/java/uk/gov/onelogin/MainActivity.kt, app/src/main/java/uk/gov/onelogin/MainActivityViewModel.kt, app/src/main/java/uk/gov/onelogin/OneLoginApplication.kt, app/src/main/java/uk/gov/onelogin/network/auth/AuthCodeExchange.kt, app/src/main/java/uk/gov/onelogin/network/auth/AuthCodeExchangeModule.kt, app/src/main/java/uk/gov/onelogin/network/http/HttpClient.kt, app/src/main/java/uk/gov/onelogin/network/http/HttpClientModule.kt, app/src/main/java/uk/gov/onelogin/network/utils/ConnectivityManagerModule.kt, app/src/main/java/uk/gov/onelogin/network/utils/OnlineChecker.kt, app/src/main/java/uk/gov/onelogin/network/utils/OnlineCheckerModule.kt, build.gradle.kts, gradle/libs.versions.toml, versions.properties
=> Add hilt dependency injection

app/src/test/java/uk/gov/onelogin/MainActivityViewModelTest.kt, gradle/libs.versions.toml
Update authorisation module to latest version
=> DCMAW-7624: Update authorisation module version

app/src/main/java/uk/gov/onelogin/features/FeaturesModule.kt, app/src/test/java/uk/gov/onelogin/MainActivityViewModelTest.kt, gradle/libs.versions.toml
=> DCMAW-7798_2: Remove feature flag

app/build.gradle.kts, app/src/main/java/uk/gov/onelogin/AppRoutes.kt, app/src/main/java/uk/gov/onelogin/network/http/HttpClient.kt, app/src/main/java/uk/gov/onelogin/ui/home/HelloWorldPostBody.kt, app/src/main/java/uk/gov/onelogin/ui/home/HomeRoutes.kt, app/src/main/java/uk/gov/onelogin/ui/home/HomeScreen.kt, gradle/libs.versions.toml
Reverts govuk-one-login/mobile-android-one-login-app#75
=> Revert "Play Integrity Spike"

app/src/main/java/uk/gov/onelogin/login/LoginRoutes.kt, app/src/main/res/values-cy/strings.xml, app/src/main/res/values/strings.xml
Add the missing routing to Home from Biometric and Password CTA
Ticket https://govukverify.atlassian.net/browse/DCMAW-7849
=> Bio opt in screen - CTA

app/src/androidTest/java/uk/gov/onelogin/login/WelcomeScreenKtTest.kt, app/src/androidTest/java/uk/gov/onelogin/ui/error/OfflineErrorScreenKtTest.kt, app/src/main/java/uk/gov/onelogin/AppRoutes.kt, app/src/main/java/uk/gov/onelogin/login/LoginRoutes.kt, app/src/main/java/uk/gov/onelogin/login/WelcomeScreenViewModel.kt, app/src/main/java/uk/gov/onelogin/login/ui/WelcomeScreen.kt, app/src/main/java/uk/gov/onelogin/ui/error/ErrorRoutes.kt, app/src/main/java/uk/gov/onelogin/ui/error/OfflineErrorScreen.kt, app/src/main/res/values-cy/strings.xml, app/src/main/res/values/strings.xml
**Work left to do: add/fix tests**
=> Network Error offline - try again

app/src/androidTest/java/uk/gov/onelogin/login/WelcomeScreenKtTest.kt, app/src/main/java/uk/gov/onelogin/login/WelcomeScreenViewModel.kt
Add support for Welsh on login web view
=> Add support for Welsh

app/src/main/java/uk/gov/onelogin/MainActivity.kt, app/src/main/java/uk/gov/onelogin/MainActivityViewModel.kt, app/src/main/java/uk/gov/onelogin/login/BioOptInViewModel.kt, app/src/main/java/uk/gov/onelogin/login/biooptin/BiometricPreferenceModule.kt, app/src/main/java/uk/gov/onelogin/tokens/SecureStoreModule.kt, app/src/main/java/uk/gov/onelogin/tokens/TokenModule.kt, app/src/main/java/uk/gov/onelogin/tokens/usecases/AutoInitialiseSecureStore.kt, app/src/main/java/uk/gov/onelogin/tokens/usecases/GetFromSecureStore.kt, app/src/main/java/uk/gov/onelogin/tokens/usecases/GetTokenExpiry.kt, app/src/main/java/uk/gov/onelogin/tokens/usecases/SaveToSecureStore.kt, app/src/main/res/values-cy/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/uk/gov/onelogin/MainActivityViewModelTest.kt, app/src/test/java/uk/gov/onelogin/extensions/CoroutinesTestExtension.kt, app/src/test/java/uk/gov/onelogin/login/BioOptInViewModelTest.kt, app/src/test/java/uk/gov/onelogin/tokens/usecases/AutoInitialiseSecureStoreTest.kt, app/src/test/java/uk/gov/onelogin/tokens/usecases/GetFromSecureStoreTest.kt, app/src/test/java/uk/gov/onelogin/tokens/usecases/GetTokenExpiryTest.kt, app/src/test/java/uk/gov/onelogin/tokens/usecases/SaveToSecureStoreTest.kt, gradle/libs.versions.toml
=> Returning user auth 

app/src/test/java/uk/gov/onelogin/MainActivityViewModelTest.kt
Add extra tests for the negative scenarios of the ticket
https://govukverify.atlassian.net/browse/DCMAW-7996
=> Add extra tests for sign out of the returning user

.github/workflows/on_pull_request.yml, config/actions/retrieve-secrets/action.yml
https://govukverify.atlassian.net/browse/DCMAW-8313
This PR changes the action used to get secrets from AWS Secrets Manager, to an official AWS secret.
See documentation for the action here - https://github.com/aws-actions/aws-secretsmanager-get-secrets
Tested in PR workflow here - https://github.com/govuk-one-login/mobile-android-one-login-app/actions/runs/8615102494/job/23609910827
=> DCMAW-8313: Change Secrets GitHub action

config/actions/retrieve-secrets/action.yml
Reverts govuk-one-login/mobile-android-one-login-app#94
=> Revert "DCMAW-8313: Change Secrets GitHub action"

app/build.gradle.kts, app/src/androidTest/java/uk/gov/onelogin/AppRoutesTest.kt, app/src/androidTest/java/uk/gov/onelogin/ui/splash/SplashScreenViewModelTest.kt, app/src/main/java/uk/gov/onelogin/MainActivity.kt, app/src/main/java/uk/gov/onelogin/MainActivityViewModel.kt, app/src/main/java/uk/gov/onelogin/login/LoginRoutes.kt, app/src/main/java/uk/gov/onelogin/repositiories/TokenRepository.kt, app/src/main/java/uk/gov/onelogin/ui/splash/SplashScreen.kt, app/src/main/java/uk/gov/onelogin/ui/splash/SplashScreenViewModel.kt, app/src/test/java/uk/gov/onelogin/MainActivityViewModelTest.kt, app/src/test/java/uk/gov/onelogin/repostiories/TokenRepositoryTest.kt, gradle/libs.versions.toml
Solves: https://govukverify.atlassian.net/browse/DCMAW-8017
=> Add LockScreen for the App

app/build.gradle.kts, app/src/main/java/uk/gov/onelogin/AppRoutes.kt, app/src/main/java/uk/gov/onelogin/developer/DeveloperPanelScreen.kt, app/src/main/java/uk/gov/onelogin/developer/DeveloperRoutes.kt, app/src/main/java/uk/gov/onelogin/developer/DeveloperTools.kt, app/src/main/java/uk/gov/onelogin/developer/tabs/AppTabScreen.kt, app/src/main/java/uk/gov/onelogin/login/LoginRoutes.kt, app/src/main/java/uk/gov/onelogin/login/ui/splash/SplashScreen.kt, app/src/main/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreen.kt, app/src/main/java/uk/gov/onelogin/mainnav/nav/MainNavRoutes.kt, app/src/main/java/uk/gov/onelogin/mainnav/ui/MainNavScreen.kt, app/src/main/java/uk/gov/onelogin/ui/home/HomeScreen.kt, app/src/main/res/values/strings.xml, gradle/libs.versions.toml
Adds a developer Portal when tapping on the Crown icon on Splash Screen/Welcome Screen or the button on Home Screen
Adds https://govukverify.atlassian.net/browse/DCMAW-8227
=> Add Developer Portal

app/src/androidTest/java/uk/gov/onelogin/ui/splash/SplashScreenViewModelTest.kt, app/src/main/java/uk/gov/onelogin/MainActivityViewModel.kt, app/src/main/java/uk/gov/onelogin/login/LoginRoutes.kt, app/src/main/java/uk/gov/onelogin/login/ui/SignInErrorScreen.kt, app/src/main/java/uk/gov/onelogin/login/ui/splash/SplashScreenViewModel.kt, app/src/main/res/values-cy/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/uk/gov/onelogin/MainActivityViewModelTest.kt
Add Sign in Error screen
[Ticket](https://govukverify.atlassian.net/browse/DCMAW-7114)
=> Add Sign in error screen

.github/workflows/on_push-develop.yml, .github/workflows/on_push-release.yml, .github/workflows/on_schedule.yml
=> Fix pipelines

app/src/androidTest/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenKtTest.kt, app/src/main/java/uk/gov/onelogin/developer/DeveloperPanelScreen.kt, app/src/main/java/uk/gov/onelogin/developer/tabs/features/FeaturesScreen.kt, app/src/main/java/uk/gov/onelogin/developer/tabs/features/FeaturesScreenViewModel.kt, app/src/main/java/uk/gov/onelogin/features/AvailableFeatures.kt, app/src/main/java/uk/gov/onelogin/features/AvailableFeaturesModule.kt, app/src/main/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenViewModel.kt, app/src/main/res/values/strings.xml
- Composable created for feature selection screen
- Screen added to developer panel
- Viewmodel created to handle logic
- `AvailableFeatures` created to handle management of available features
Resolves: DCMAW-8268
=> Create Feature Flag Selection Tab

app/src/main/java/uk/gov/onelogin/network/StsAuthenticationProvider.kt, app/src/main/java/uk/gov/onelogin/network/usecase/HelloWorldApiCall.kt
- Remove 'unchecked' casts for `ApiResponse`
- Make functional interface
=> Fix sonar smells

app/src/androidTest/java/uk/gov/onelogin/ui/profile/ProfileScreenKtTest.kt, app/src/main/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenViewModel.kt, app/src/main/java/uk/gov/onelogin/ui/LocaleUtils.kt, app/src/main/java/uk/gov/onelogin/ui/components/Color.kt, app/src/main/java/uk/gov/onelogin/ui/components/EmailHeader.kt, app/src/main/java/uk/gov/onelogin/ui/profile/ProfileScreen.kt, app/src/main/res/drawable/arrow_right_icon.xml, app/src/main/res/drawable/external_link_icon.xml, app/src/main/res/values-cy/strings.xml, app/src/main/res/values/strings.xml, config/actions/setup-runner/action.yml
https://govukverify.atlassian.net/browse/DCMAW-8774
=> Add content on profile screen

app/src/main/AndroidManifest.xml
=> fix/DCMAW-8592: Fix sonar issue

app/src/main/java/uk/gov/onelogin/credentialchecker/BiometricManager.kt, app/src/main/java/uk/gov/onelogin/login/usecase/HandleLogin.kt, app/src/main/java/uk/gov/onelogin/login/usecase/VerifyIdToken.kt, app/src/main/java/uk/gov/onelogin/tokens/usecases/SaveTokenExpiry.kt, app/src/main/res/values/themes.xml, app/src/main/res/xml/data_extraction_rules.xml, gradle/libs.versions.toml
- Mostly making sure interfaces that should be `fun interface` are sorted.
- Removing some commented code
=> fix/DCMAW-9085: Fix Sonar Issues

app/src/main/res/values-cy/strings.xml, app/src/main/res/values/strings.xml
Fix bug here -> https://govukverify.atlassian.net/browse/DCMAW-8774?focusedCommentId=153050
=> Fix profile copy for cy

app/src/androidTest/java/uk/gov/onelogin/ui/home/HomeScreenViewModelTest.kt, app/src/main/java/uk/gov/onelogin/login/usecase/VerifyIdToken.kt, app/src/main/java/uk/gov/onelogin/tokens/TokenModule.kt, app/src/main/java/uk/gov/onelogin/tokens/usecases/GetEmail.kt, app/src/main/java/uk/gov/onelogin/ui/home/HomeScreen.kt, app/src/main/java/uk/gov/onelogin/ui/home/HomeScreenViewModel.kt, app/src/test/java/uk/gov/onelogin/login/usecase/VerifyIdTokenTest.kt, app/src/test/java/uk/gov/onelogin/tokens/usecases/GetEmailImplTest.kt
https://govukverify.atlassian.net/browse/DCMAW-8650
=> Add email to home

app/src/androidTest/java/uk/gov/onelogin/ui/profile/ProfileScreenViewModelTest.kt, app/src/main/java/uk/gov/onelogin/ui/profile/ProfileScreen.kt, app/src/main/java/uk/gov/onelogin/ui/profile/ProfileScreenViewModel.kt
https://govukverify.atlassian.net/browse/DCMAW-8780
=> Add email to the ProfileScreen

app/build.gradle.kts, app/src/build/google-services.json, app/src/staging/google-services.json, build.gradle.kts, gradle/libs.versions.toml
- respective congif .json added to build and staging flavours
- google-services plugin added to project and app build.gradle files
- some configuration in app/build.gradle to handle disabling the google-services plugin for production variants
Resolves: DCMAW-8458
=> DCMAW-8458: Add GA configuration .json

.github/workflows/on_push-develop.yml
Add unit tests to on_push workflow
=> ci/Fix on_push workflow

app/src/androidTest/java/uk/gov/onelogin/FlakyTestRule.kt, app/src/androidTest/java/uk/gov/onelogin/e2e/LoginTest.kt, app/src/androidTest/java/uk/gov/onelogin/login/ui/SignInErrorScreenTest.kt, app/src/androidTest/java/uk/gov/onelogin/signOut/ui/SignOutScreenKtTest.kt, app/src/androidTest/java/uk/gov/onelogin/ui/error/SignInErrorScreenTest.kt, app/src/androidTest/java/uk/gov/onelogin/ui/error/SignOutErrorScreenTest.kt, app/src/main/java/uk/gov/onelogin/login/ui/SignInErrorScreen.kt, app/src/main/java/uk/gov/onelogin/signOut/SignOutRoutes.kt, app/src/main/java/uk/gov/onelogin/signOut/domain/SignOutUseCase.kt, app/src/main/java/uk/gov/onelogin/signOut/ui/SignOutScreen.kt, app/src/main/java/uk/gov/onelogin/tokens/usecases/RemoveAllSecureStoreData.kt, app/src/main/java/uk/gov/onelogin/ui/error/ErrorRoutes.kt, app/src/main/java/uk/gov/onelogin/ui/error/SignOutErrorScreen.kt, app/src/main/res/values-cy/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/uk/gov/onelogin/signOut/domain/SignOutUseCaseTest.kt, app/src/test/java/uk/gov/onelogin/tokens/usecases/GetEmailImplTest.kt, app/src/test/java/uk/gov/onelogin/tokens/usecases/RemoveAllSecureStoreDataTest.kt
https://govukverify.atlassian.net/browse/DCMAW-9096
=> Sign out error screen

Gemfile.lock, app/src/main/java/uk/gov/onelogin/developer/tabs/networking/NetworkingViewModel.kt
=> fix/DCMAW-9806: Bump REXML version

.github/workflows/on_pull_request.yml, .github/workflows/on_push-develop.yml, .github/workflows/on_schedule.yml, app/build.gradle.kts, app/src/androidTest/java/uk/gov/onelogin/e2e/LoginTest.kt, app/src/androidTest/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreenKtTest.kt, app/src/androidTest/java/uk/gov/onelogin/mainnav/ui/MainNavScreenTest.kt, app/src/androidTest/java/uk/gov/onelogin/ui/wallet/WalletScreenTest.kt, app/src/main/AndroidManifest.xml, app/src/main/java/uk/gov/onelogin/mainnav/ui/MainNavScreen.kt, app/src/main/java/uk/gov/onelogin/network/di/NetworkModule.kt, app/src/main/java/uk/gov/onelogin/optin/ProviderModule.kt, app/src/main/java/uk/gov/onelogin/optin/data/AnalyticsOptInLocalSource.kt, app/src/main/java/uk/gov/onelogin/optin/data/FirebaseAnalyticsOptInSource.kt, app/src/main/java/uk/gov/onelogin/optin/domain/repository/OptInRepository.kt, app/src/main/java/uk/gov/onelogin/optin/ui/IODispatcherQualifier.kt, app/src/main/java/uk/gov/onelogin/ui/wallet/WalletScreenViewModel.kt, app/src/main/java/uk/gov/onelogin/wallet/WalletModule.kt, gradle/libs.versions.toml
**Ticket Link:**
[DCMAW-10145](https://govukverify.atlassian.net/browse/DCMAW-10145)
[DCMAW-8582](https://govukverify.atlassian.net/browse/DCMAW-8582)
- add dependency on Wallet SDK package and use it in the OL codebase
**Evidence:**
_Scenario 1_: Wallet initialised from within the strategic app
GIVEN I’m a user on the strategic app
AND I’m on the home page
WHEN I tap the Wallet tab button
THEN I see the Wallet screen
**Build Env**
https://github.com/user-attachments/assets/3c3736ab-b98b-4c35-9402-541963d4295f
**Staging Env**
https://github.com/user-attachments/assets/08171a32-dad7-4db3-a765-dc82af2a6b56
Resolves: DCMAW-10145, DCMAW-8582
[DCMAW-10145]: https://govukverify.atlassian.net/browse/DCMAW-10145?atlOrigin=eyJpIjoiNWRkN …
=> feat: Integrate Wallet

app/src/androidTest/java/uk/gov/onelogin/signOut/ui/SignedOutInfoScreenTest.kt, app/src/main/AndroidManifest.xml, app/src/main/java/uk/gov/onelogin/signOut/ui/SignedOutInfoScreen.kt, app/src/main/res/values-cy/strings.xml, app/src/main/res/values/strings.xml, gradle/libs.versions.toml
[DCMAW-9590](https://govukverify.atlassian.net/browse/DCMAW-9590)
- write instrumentation tests for the screen
- create the screen
- update the mobile-ui version used
- update internal column modifier for content on SignedOutInfoScreen
**Evidence:**
Documentation:
[Figma Designs](https://www.figma.com/design/YjfRo1DTO7cxQM4w1yKXK3/Strategic-App?node-id=15365-91580&t=miLEGimjkg81uwHR-4)
Resolves: DCMAW-9590
[DCMAW-9590]: https://govukverify.atlassian.net/browse/DCMAW-9590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add SignedOutInfoScreen

app/src/main/AndroidManifest.xml
- add AD_ID permission to the manifest - AD_ID is now used due to firebase
Resolves: DCMAW-9185
=> fix: Solve Google Play API AD_ID issue

LICENSE
Added MIT License file as per the GDS Way:
https://gds-way.digital.cabinet-office.gov.uk/manuals/licensing.html#use-mit
=> chore: added license

app/src/androidTest/java/uk/gov/onelogin/credentialChecker/BiometricManagerTest.kt, app/src/androidTest/java/uk/gov/onelogin/login/ui/biooptin/BioOptInScreenTest.kt, app/src/androidTest/java/uk/gov/onelogin/optin/ui/OptInScreenTest.kt, app/src/androidTest/java/uk/gov/onelogin/optin/ui/PrivacyNoticeTest.kt, app/src/main/java/uk/gov/onelogin/core/meta/ExcludeFromJacocoGeneratedReport.kt, app/src/main/java/uk/gov/onelogin/core/meta/ScreenPreview.kt, app/src/main/java/uk/gov/onelogin/credentialchecker/BiometricManagerImpl.kt, app/src/main/java/uk/gov/onelogin/credentialchecker/BiometricStatus.kt, app/src/main/java/uk/gov/onelogin/login/ui/biooptin/BiometricsOptInScreen.kt, app/src/main/java/uk/gov/onelogin/login/ui/splash/SplashScreen.kt, app/src/main/java/uk/gov/onelogin/login/ui/welcome/WelcomeScreen.kt, app/src/main/java/uk/gov/onelogin/optin/ui/OptInScreen.kt, app/src/main/java/uk/gov/onelogin/optin/ui/PrivacyNotice.kt, app/src/main/java/uk/gov/onelogin/signOut/ui/SignedOutInfoScreen.kt, app/src/test/java/uk/gov/onelogin/core/delete/domain/MultiCleanerTest.kt, app/src/test/java/uk/gov/onelogin/credentialchecker/BiometricStatusTest.kt, app/src/test/java/uk/gov/onelogin/optin/domain/SingleChoiceTest.kt, app/src/test/java/uk/gov/onelogin/optin/domain/repository/AnalyticsOptInRepositoryTest.kt, app/src/test/java/uk/gov/onelogin/optin/ui/OptInUIStateTest.kt
- [Ticket DCMAW-10391](https://govukverify.atlassian.net/browse/DCMAW-10391)
- [Confluence Document](https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4598956070/Sonar+investigation)
- Increase code coverage for package credentialChecker
- Increase code coverage for package optin
- Increase code coverage for package core delete
- No evidence provided / sonar cloud code coverage % is the evidence I guess
=> Fix: DCMAW-10391 increase coverage

app/src/androidTest/java/uk/gov/onelogin/mainnav/ui/MainNavScreenTest.kt, app/src/main/java/uk/gov/onelogin/features/AvailableFeatures.kt, app/src/main/java/uk/gov/onelogin/features/FeaturesModule.kt, app/src/main/java/uk/gov/onelogin/features/WalletFeatureFlag.kt, app/src/main/java/uk/gov/onelogin/features/domain/FeatureFlagSetter.kt, app/src/main/java/uk/gov/onelogin/mainnav/ui/MainNavScreen.kt, app/src/main/java/uk/gov/onelogin/wallet/WalletScreenViewModel.kt, app/src/test/java/uk/gov/onelogin/TestUtils.kt, app/src/test/java/uk/gov/onelogin/features/AvailableFeaturesTest.kt, app/src/test/java/uk/gov/onelogin/features/domain/FeatureFlagSetterImplTest.kt, app/src/test/java/uk/gov/onelogin/wallet/WalletScreenViewModelTest.kt
[DCMAW-9788](https://govukverify.atlassian.net/browse/DCMAW-9788)
**Evidence:**
**_AC1_**
Build
https://github.com/user-attachments/assets/87a9edb7-acb0-4dac-a02f-cf66bb66d5e8
Staging
https://github.com/user-attachments/assets/50f2bc04-2d23-48d0-b609-3ade43bcd063
**_AC2_**
_This has been tested with a temporary stack (not the `/appInfo` endpoint - the logic has not been changed so it would work the same with any endpoint - functionality tested._
```
{
"apps": {
"android": {
"minimumVersion": "0.0.0",
"releaseFlags": {
"walletVisibleViaDeepLink": true,
"walletVisibleIfExists": true,
"walletVisibleToAll": true
},
"available": true,
"featureFlags" : {
"appCheckEnabled": false
}
},
"iOS": {
"minimumVersion": "1.0.0",
"releaseFlags": { …
```
=> feat: Add WalletFeatureFlag

app/src/androidTest/java/uk/gov/onelogin/optin/ui/OptInScreenTest.kt, app/src/androidTest/java/uk/gov/onelogin/ui/profile/ProfileScreenTest.kt, app/src/main/java/uk/gov/onelogin/ui/profile/ProfileScreen.kt, app/src/main/java/uk/gov/onelogin/ui/profile/ProfileScreenViewModel.kt, app/src/main/res/values-cy/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/uk/gov/onelogin/ui/profile/ProfileScreenViewModelTest.kt
- [Ticket DCMAW-10391](https://govukverify.atlassian.net/browse/DCMAW-10391)
- [Confluence Document](https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4598956070/Sonar+investigation)
- Increase code coverage for code using UriHandler
- No evidence provided / sonar cloud code coverage % is the evidence I guess
=> Fix: DCMAW 10391 increase coverage

app/src/test/java/uk/gov/onelogin/credentialchecker/BiometricStatusTest.kt, app/src/test/java/uk/gov/onelogin/login/biooptin/BiometricPreferenceTest.kt, app/src/test/java/uk/gov/onelogin/optin/domain/SingleChoiceTest.kt, app/src/test/java/uk/gov/onelogin/optin/ui/OptInUIStateTest.kt
- [Ticket DCMAW-10391](https://govukverify.atlassian.net/browse/DCMAW-10391)
- [Confluence Document](https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4598956070/Sonar+investigation)
- Increase code coverage for enums
- It is difficult to see if this increases coverage as there is only added tests, so sonar won't show, but experimentation indicated it would.
- No evidence provided / sonar cloud code coverage % is the evidence I guess
=> Feat: DCMAW 10391 enum coverage

app/src/debug/res/xml/backup_rules.xml, app/src/debug/res/xml/data_extraction_rules.xml
- [Ticket DCMAW-10352](https://govukverify.atlassian.net/browse/DCMAW-10352)
- Add backup_rules.xml to exclude backing up files, shared preferences, and databases
- Add data_extraction_rules.xml to exclude backing up files, shared preferences, and databases
https://github.com/user-attachments/assets/b1d3c411-30dd-4a6e-88c9-2c0559dfc72c
- ~[ ] Complete automated Testing:~
* ~[ ] Unit Tests.~
* ~[ ] Integration Tests.~
* ~[ ] Instrumentation / Emulator Tests.~
- ~[ ] Review [Accessibility considerations].~
=> fix: Turn off backups for debug

.github/dependabot.yml, .github/workflows/on_pull_request.yml, .github/workflows/on_push-develop.yml, .github/workflows/on_push-release.yml, .github/workflows/on_schedule.yml, config/actions/bump-version/action.yml, config/actions/bundle-reports/action.yml, config/actions/determine-semver-bump/action.yml, config/actions/gradle-connected-test/action.yml, config/actions/retrieve-secrets/action.yml, config/actions/setup-runner/action.yml
https://govukverify.atlassian.net/browse/PSREDEV-1911
=> ops: standardise all github actions in response to incoming breaking changes from github

.github/workflows/on_push-release.yml
Pin existing workflows to Ubuntu 22
=> DCMAW-10545 Change runs on to ubuntu-22.04

app/src/main/java/uk/gov/onelogin/wallet/WalletModule.kt, gradle/libs.versions.toml, local.properties.example, settings.gradle.kts
**Ticket Link:**
[DCMAW-11043](https://govukverify.atlassian.net/browse/DCMAW-11043)
**Description Of Changes:**
- update `WalletSdk` to v1.38.0 (latest version)
- add more specific information for the `local.properties` version
**Evidence**:
https://github.com/user-attachments/assets/46a2c6cf-e6e4-4a88-a8e6-40654423bae5
Resolves: DCMAW-11043
[DCMAW-11043]: https://govukverify.atlassian.net/browse/DCMAW-11043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Update to latest WalletSdk version (v1.38.0)

app/src/main/res/values-cy/strings.xml, app/src/main/res/values/strings.xml
**Ticket Link:**
[DCMAW-10175](https://govukverify.atlassian.net/browse/DCMAW-10175)
**Description Of Changes:**
- updated english copy
- updated welsh copy
**Evidence**
[DCMAW-10175]: https://govukverify.atlassian.net/browse/DCMAW-10175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: update Analytics opt-in copy

app/src/androidTest/java/uk/gov/onelogin/ui/error/generic/GenericErrorAnalyticsViewModelTest.kt, app/src/androidTest/java/uk/gov/onelogin/ui/error/generic/GenericErrorScreenTest.kt, app/src/androidTest/java/uk/gov/onelogin/ui/error/offline/OfflineErrorAnalyticsViewModelTest.kt, app/src/androidTest/java/uk/gov/onelogin/ui/error/offline/OfflineErrorScreenKtTest.kt, app/src/androidTest/java/uk/gov/onelogin/ui/error/signin/SignInErrorAnalyticsViewModelTest.kt, app/src/androidTest/java/uk/gov/onelogin/ui/error/signin/SignInErrorScreenTest.kt, app/src/main/java/uk/gov/onelogin/login/LoginGraphObject.kt, app/src/main/java/uk/gov/onelogin/ui/error/ErrorGraphObject.kt, app/src/main/java/uk/gov/onelogin/ui/error/generic/GenericErrorAnalyticsViewModel.kt, app/src/main/java/uk/gov/onelogin/ui/error/generic/GenericErrorScreen.kt, app/src/main/java/uk/gov/onelogin/ui/error/offline/OfflineErrorAnalyticsViewModel.kt, app/src/main/java/uk/gov/onelogin/ui/error/offline/OfflineErrorScreen.kt, app/src/main/java/uk/gov/onelogin/ui/error/signin/SignInErrorAnalyticsViewModel.kt, app/src/main/java/uk/gov/onelogin/ui/error/signin/SignInErrorScreen.kt, app/src/main/res/values/screen_ids.xml, app/src/main/res/values/strings.xml
[DCMAW-8416](https://govukverify.atlassian.net/browse/DCMAW-8416)
[DCMAW-8419](https://govukverify.atlassian.net/browse/DCMAW-8419)
[DCMAW-8422](https://govukverify.atlassian.net/browse/DCMAW-8422)
- add GA4 analytics for `GenericErrorScreen`
- add GA4 analytics for `SignInErrorScreen`
- add GA4 analytics for `OfflineErrorScreen`
**Evidence:**
_DCMAW-8416_ - All ACs, except disabled analytics
`GenericErrorScreen` is not used in the codebase as a navigation destination - cannot get logs/ video of it since not used. The GA4 should be triggered as it's the same set-up as the two screens below. I can walk through the code and show how it's implemented if it helps.
_DCMAW-8419_ - All ACs, except disabled analytics …
=> feat: Add GA4 analytics for `ui.error` package

app/src/androidTest/java/uk/gov/onelogin/mainnav/ui/MainNavAnalyticsViewModelTest.kt, app/src/androidTest/java/uk/gov/onelogin/mainnav/ui/MainNavScreenTest.kt, app/src/main/java/uk/gov/onelogin/mainnav/ui/MainNavAnalyticsViewModel.kt, app/src/main/java/uk/gov/onelogin/mainnav/ui/MainNavScreen.kt, config/styles/config/vocabularies/Base/accept.txt
DCMAW-8823
- add GA4 analytics for the `MainNavScreen` for `eventButtonIcon` when any of the tabs are being clicked
**Evidence:**
_AC1a/ Ac2a/ AC3a_
https://github.com/user-attachments/assets/152c04d9-358d-4897-990d-435534fb6032
```
2025-02-18 11:26:39.274 20082-20082 FirebaseAnalyticsLogger uk.gov.onelogin.build                D  Firebase event sent with: Bundle[{saved_doc_type=undefined, taxonomy_level1=one login mobile application, taxonomy_level2=settings, taxonomy_level3=undefined, text=Settings, type=icon, primary_publishing_organisation=government digital service - digital identity, organisation=<OT1056>}]
2025-02-18 11:26:42.811 20082-20082 FirebaseAnalyticsLogger uk.gov.onelogin.build                D  Firebase event sent with: …
```
=> feat: Add GA4 analytics for `MainNavScreen` (`BottomAppBar`)

app/src/androidTest/java/uk/gov/onelogin/ui/components/SimpleTextPageTest.kt, app/src/main/res/values/strings.xml
Ticket Link:
[DCMAW-10225](https://govukverify.atlassian.net/browse/DCMAW-10225)
Description Of Changes:
fixed app name to have spaces in between
**Evidence**
[DCMAW-10225]: https://govukverify.atlassian.net/browse/DCMAW-10225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Fix app name

core/src/main/res/values-cy/strings.xml, core/src/main/res/values/strings.xml
[DCMAW-11106](https://govukverify.atlassian.net/browse/DCMAW-11106)
- amend strings for `SignOutErrorScreen` with the new designs provided
**Evidence:**
_Welsh 1_
https://github.com/user-attachments/assets/819ec710-0fb4-4d31-b2e4-a8d8bdcec59d
_Scenario 1_
https://github.com/user-attachments/assets/bb55eae7-54b6-4539-8027-bad29664ab0c
[DCMAW-11106]: https://govukverify.atlassian.net/browse/DCMAW-11106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Content change re-auth landing page

app/src/androidTest/java/uk/gov/onelogin/e2e/LoginTest.kt, core/src/main/res/values-cy/strings.xml, core/src/main/res/values/strings.xml, features/src/androidTest/java/uk/gov/onelogin/features/login/ui/welcome/WelcomeBodyTest.kt, features/src/androidTest/java/uk/gov/onelogin/features/login/ui/welcome/WelcomeScreenTest.kt, features/src/main/java/uk/gov/onelogin/features/login/ui/signin/welcome/WelcomeScreen.kt
- Update Sign in page copy
- Updated the UI test to reflect the changes.
https://github.com/user-attachments/assets/23d7646b-18a5-4e91-9edb-573253a8007f
=> feat: Update sign-in screen text

core/src/main/java/uk/gov/onelogin/core/ui/components/EmailSection.kt, core/src/main/java/uk/gov/onelogin/core/ui/pages/TitledPage.kt, core/src/test/java/uk/gov/onelogin/core/ui/components/EmailSectionTest.kt, features/src/main/java/uk/gov/onelogin/features/developer/ui/criorchestratormenu/CriOrchestratorDevMenuScreen.kt, features/src/main/java/uk/gov/onelogin/features/home/ui/HomeScreen.kt, features/src/main/java/uk/gov/onelogin/features/settings/ui/SettingsScreen.kt, features/src/test/java/uk/gov/onelogin/features/settings/ui/SettingsScreenTest.kt
Resolves: [DCMAW-12635](https://govukverify.atlassian.net/browse/DCMAW-12635)
[DCMAW-12635]: https://govukverify.atlassian.net/browse/DCMAW-12635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> - Fix overlapping text in settings screen

features/src/main/java/uk/gov/onelogin/features/signout/domain/SignOutUIState.kt, features/src/main/java/uk/gov/onelogin/features/signout/ui/SignOutScreen.kt, features/src/test/java/uk/gov/onelogin/features/signout/ui/SignOutBodyTest.kt, features/src/test/java/uk/gov/onelogin/features/signout/ui/SignOutBodyWalletTest.kt
[Tutorial for writing good descriptions]: https://cbea.ms/git-commit/
[//]: # (Be mindful that the PR title also needs to follow conventional commit standards)
- this refactor will fix accessibility issues for the bullet lists
[//]: # (e.g. "- Create 'androidLibrary' Gradle module.")
https://github.com/user-attachments/assets/6ceb4387-7a1a-40c8-827a-26a17f0cffaf
[//]: # (Screenshots / uploaded videos go here)
[Sonar cloud report]: https://sonarcloud.io/project/overview?id=di-mobile-android-ui
Resolves: DCMAW-12637
=> fix: Update `SignOutScreen` to use v2 components/ patterns

features/src/main/java/uk/gov/onelogin/features/login/ui/signin/welcome/WelcomeScreen.kt
[Tutorial for writing good descriptions]: https://cbea.ms/git-commit/
[//]: # (Be mindful that the PR title also needs to follow conventional commit standards)
- only send the loading screen GA4 event instead of both Welcome Screen and loading one
[//]: # (e.g. "- Create 'androidLibrary' Gradle module.")
`WelcomeScreen` screen id: `30a6b339-75a8-44a2-a79a-e108546419bf` (should only be triggered when landing on the sign in place, but not on redirect back to teh app after login)
`Loading` screen id: `0672f0fa-8126-479b-b191-8e750fa3d909` (this is expected to be triggered both before pressing sign-in and when returning/ being redirected to the app after login on teh web pop-up)
https://github.com/user-attachments/assets/9f72b71e-358c-4536-ac52-17d61bff81d4
[//]: # (Screenshots / uploaded …
=> feat: Remove logging `screenEvent` when redirected from login to app

app/proguard-rules.pro
- Add proguard rule
Resolves: DCMAW-12972
=> DCMAW-12972: Update the content tiles on the home page

.github/workflows/on_push-develop.yml
=> fix: Fix duplicate is name in workflow

.github/workflows/on_push-develop.yml
=> fix: Remove unnecessary quotes

.github/workflows/on_push-develop.yml
=> ci: Remove possible issue in the aab path

.github/workflows/on_push-develop.yml
- revert temporary changes done for the on-push-develop
- add prod and int to publishing and bunldes in the workflow
Resolves: DCMAW-7021
=> ci: Publish prod and int to playstore(2/2)

core/src/main/res/values-cy/strings.xml, core/src/main/res/values/urls.xml
=> feat: change accessibility URL

.github/workflows/on_push-develop.yml
=> ci: Publish only staging and build temporarily

features/src/main/java/uk/gov/onelogin/features/login/ui/signin/splash/SplashScreen.kt
- Replace gdsTheme with m3.GdsTheme in splash screen
Resolves: DCMAW-13077
| Old | New |
|--------|--------|
| ![splash_old](https://github.com/user-attachments/assets/9a704389-cb7a-498e-9a6f-be910c71f7d5) | ![splash_new](https://github.com/user-attachments/assets/43d05bca-dc42-4ad8-9c07-e33186c7f663) |
=> DCMAW-13077: One Login GDSTheme

core/src/main/res/values-cy/strings.xml, core/src/main/res/values/urls.xml
https://github.com/user-attachments/assets/ed86e211-6f61-47ba-8b22-e035924ea7a8
Resolves: DCMAW-13499
=> feat: Change urls for Using your GOV.UK One Login app on SettingsScreen

core/src/main/res/values-cy/strings.xml, core/src/main/res/values/urls.xml
https://github.com/user-attachments/assets/ea8da529-8303-4a6a-8b86-149bbae93403
Resolves: DCMAW-13530
=> feat: Update link for Manage your details on SettingsScreen

app/src/main/AndroidManifest.xml, config/actions/setup-runner/action.yml
- Fixing auto verify for App Link in manifest
- Removal of 'wallet' App Link
=> release/1.0.2 - fixing DCMAW-13800

app/src/androidTest/java/uk/gov/onelogin/criorchestrator/CriOrchestratorModuleTest.kt, app/src/main/java/uk/gov/onelogin/criorchestrator/CriOrchestratorModule.kt, features/src/main/java/uk/gov/onelogin/features/appinfo/AppInfoUtils.kt
- Update default CRI configuration
- Update play store app link
=> release/1.0.3 - fixing DCMAW-13816

app/src/androidTest/java/uk/gov/onelogin/navigation/graphs/SignOutGraphObjectTest.kt, app/src/main/java/uk/gov/onelogin/navigation/graphs/SignOutGraphObject.kt, core/src/main/java/uk/gov/onelogin/core/navigation/data/SignOutRoutes.kt, core/src/main/res/values-cy/strings.xml, core/src/main/res/values/screen_ids.xml, core/src/main/res/values/strings.xml, features/src/main/java/uk/gov/onelogin/features/signout/ui/SignOutViewModel.kt, features/src/main/java/uk/gov/onelogin/features/signout/ui/info/SignedOutInfoAnalyticsViewModel.kt, features/src/main/java/uk/gov/onelogin/features/signout/ui/info/SignedOutInfoScreen.kt, features/src/main/java/uk/gov/onelogin/features/signout/ui/info/SignedOutInfoViewModel.kt, features/src/main/java/uk/gov/onelogin/features/signout/ui/success/SignOutSuccess.kt, features/src/main/java/uk/gov/onelogin/features/signout/ui/success/SignOutSuccessAnalyticsViewModel.kt, features/src/main/java/uk/gov/onelogin/features/signout/ui/success/SignOutSuccessViewModel.kt, features/src/test/java/uk/gov/onelogin/features/signout/ui/SignOutScreenTest.kt, features/src/test/java/uk/gov/onelogin/features/signout/ui/SignOutViewModelTest.kt, features/src/test/java/uk/gov/onelogin/features/signout/ui/info/SignedOutInfoAnalyticsViewModelTest.kt, features/src/test/java/uk/gov/onelogin/features/signout/ui/info/SignedOutInfoScreenTest.kt, features/src/test/java/uk/gov/onelogin/features/signout/ui/info/SignedOutInfoViewModelTest.kt, features/src/test/java/uk/gov/onelogin/features/signout/ui/success/SignOutSuccessTest.kt, features/src/test/java/uk/gov/onelogin/features/signout/ui/success/SignOutSuccessViewmodelTest.kt
[Tutorial for writing good descriptions]: https://cbea.ms/git-commit/
[//]: # (Be mindful that the PR title also needs to follow conventional commit standards)
- create `SignOutSuccess`
- add GA4 for the screen
[//]: # (e.g. "- Create 'androidLibrary' Gradle module.")
https://github.com/user-attachments/assets/0c83d7ef-6eb4-4b97-ab0c-650ad821e7d8
https://github.com/user-attachments/assets/0931ea2a-b466-48e6-9981-2e552577b798
https://github.com/user-attachments/assets/2dc1e44b-7ae3-47d8-abb8-7d7a86fe24d4
_GA4_
Wallet Screen and primary button:
```
2025-06-10 16:01:03.216 21718-21718 FirebaseAnalyticsLogger uk.gov.onelogin.build                D  Firebase event sent with: Bundle[{language=en, screen_class=ea627a8b-1f24-44c3-8540-0684c26d390f, saved_doc_type=undefined, taxonomy_level1=one …
```
=> feat: Sign out confirmation screen

core/src/main/res/values/strings.xml
- add id check app string name
=> fix: add id check sdk app name

app/src/androidTest/java/uk/gov/onelogin/e2e/LoginTest.kt, features/src/main/java/uk/gov/onelogin/features/login/ui/signin/welcome/WelcomeScreen.kt
- Fix missing loading screen issue
Resolves: DCMAW-14186
https://github.com/user-attachments/assets/65626790-3b06-4d8f-aefa-09cc35a9d0b8
=> DCMAW-14186: Loading screen not displayed on return from login redirect (post setting local auth preference)

app/src/main/AndroidManifest.xml, app/src/main/java/uk/gov/onelogin/MainActivity.kt, app/src/main/java/uk/gov/onelogin/mainnav/graphs/BottomNavGraph.kt
- change the MainActivity launch mode to `singleTop`
- add navigation based entry points for deeplinks on the WalletScreen
**Evidence:**
https://github.com/user-attachments/assets/d5140c3e-00f3-4b43-9ab4-8bc27aedff7c
https://github.com/user-attachments/assets/24f6fef4-02c1-4ecd-82df-071d8dc79273
Resolves: DCMAW-14006
=> fix: Fix launcher issue to maintain context

README.md
- no functionality changed, this PR is only to enable a merge to `main` to push the tag `1.2.0`
=> fix: Fix to enable publishing 1.2.0

features/src/main/java/uk/gov/onelogin/features/login/domain/signin/loginredirect/HandleLoginRedirectImpl.kt, features/src/main/java/uk/gov/onelogin/features/login/domain/signin/remotelogin/HandleRemoteLoginImpl.kt, features/src/test/java/uk/gov/onelogin/features/login/domain/signin/loginredirect/HandleLoginRedirectTest.kt, features/src/test/java/uk/gov/onelogin/features/login/domain/signin/remotelogin/HandleRemoteLoginTest.kt
- this should reduce the app crashes we are seeing in Prod
=> fix: Add more error handling for the login flow

core/build.gradle.kts, core/src/main/res/values/strings.xml, core/src/test/java/uk/gov/onelogin/core/tokens/domain/retrieve/GetFromOpenSecureStoreImplTest.kt, core/src/test/java/uk/gov/onelogin/core/tokens/domain/retrieve/GetPersistentIdImplTest.kt, core/src/test/java/uk/gov/onelogin/core/ui/pages/loading/LoadingScreenAnalyticsViewModelTest.kt, core/src/testFixtures/java/uk/gov/onelogin/core/utils/GAUtils.kt, core/src/testFixtures/java/uk/gov/onelogin/core/utils/MockitoHelper.kt, features/build.gradle.kts, features/src/main/java/uk/gov/onelogin/features/error/ui/signin/SignInErrorAnalyticsViewModel.kt, features/src/main/java/uk/gov/onelogin/features/error/ui/unavailable/AppUnavailableAnalyticsViewModel.kt, features/src/main/java/uk/gov/onelogin/features/error/ui/update/OutdatedAppErrorAnalyticsViewModel.kt, features/src/test/java/uk/gov/onelogin/features/error/ui/generic/GenericErrorAnalyticsViewModelTest.kt, features/src/test/java/uk/gov/onelogin/features/error/ui/offline/OfflineErrorAnalyticsViewModelTest.kt, features/src/test/java/uk/gov/onelogin/features/error/ui/signin/SignInErrorAnalyticsViewModelTest.kt, features/src/test/java/uk/gov/onelogin/features/error/ui/unavailable/AppUnavailableAnalyticsViewModelTest.kt, features/src/test/java/uk/gov/onelogin/features/error/ui/update/OutdatedAppErrorAnalyticsViewModelTest.kt, features/src/test/java/uk/gov/onelogin/features/home/ui/HomeScreenAnalyticsViewModelTest.kt, features/src/test/java/uk/gov/onelogin/features/login/domain/signin/locallogin/HandleLocalLoginTest.kt, features/src/test/java/uk/gov/onelogin/features/login/ui/splash/SplashScreenAnalyticsViewModelTest.kt, features/src/test/java/uk/gov/onelogin/features/login/ui/welcome/SignInAnalyticsViewModelTest.kt, features/src/test/java/uk/gov/onelogin/features/settings/ui/SettingsAnalyticsViewModelTest.kt, features/src/test/java/uk/gov/onelogin/features/signout/ui/SignOutAnalyticsViewModelTest.kt, features/src/test/java/uk/gov/onelogin/features/signout/ui/info/SignedOutInfoAnalyticsViewModelTest.kt, gradle.properties, gradle/libs.versions.toml
[DCMAW-14533](https://govukverify.atlassian.net/browse/DCMAW-14533): Updating logging package and refactor tests
Change analytics events to Error for BioOptOutScreen and GoToSettingsScreen 
Check is_error parameter in tests
[DCMAW-14533]: https://govukverify.atlassian.net/browse/DCMAW-14533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DCMAW-14533: Updating logging package and refactor tests for is_error parameter

features/build.gradle.kts
Merge release 1.7.0 to develop
=> merge from main 

app/src/main/java/uk/gov/onelogin/MainActivityViewModel.kt, app/src/test/java/uk/gov/onelogin/MainActivityViewModelIntentTest.kt, app/src/test/java/uk/gov/onelogin/MainActivityViewModelTest.kt, features/src/main/java/uk/gov/onelogin/features/login/ui/signin/splash/SplashScreenViewModel.kt, features/src/test/java/uk/gov/onelogin/features/login/ui/splash/SplashScreenTest.kt, features/src/test/java/uk/gov/onelogin/features/login/ui/splash/SplashScreenViewModelTest.kt, features/src/testBuild/java/uk/gov/onelogin/features/login/ui/splash/SplashScreenDevMenuTest.kt, features/src/testIntegration/kotlin/uk/gov/onelogin/features/login/ui/splash/SplashScreenDevMenuTest.kt, features/src/testProduction/java/uk/gov/onelogin/features/login/ui/splash/SplashScreenDevMenuTest.kt, features/src/testStaging/java/uk/gov/onelogin/features/login/ui/splash/SplashScreenDevMenuTest.kt
https://github.com/user-attachments/assets/6d7259d7-64d3-4c7d-aab8-4ae38b40172f
=> fix: Fix accessing app without internet after quitting it
